runtime: nodejs12
handlers:
  # Serve all static files with url ending with a file extension
  - url: /(.*\..+)$
    static_files: public/\1
    upload: public/(.*\..+)$
  # Catch all handler to index.js
  - url: /.*
    static_die: src/index.js
