runtime: nodejs12
handlers:
  # Serve all static files with url ending with a file extension
  - url: /(.*\..+)$
    static_files: public/\1
    upload: build/(.*\..+)$
  # Catch all handler to index.html
  - url: /.*
    script: auto
  # - url: /.*
  #   static_files: public/index.html
  #   upload: public/index.html