name: ci-master-program-front
on:
  push:
    branches: [main]
  # pull_request:
  #   branches: [main]

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      #Checking if the app build successfully
      - name: npm install
        run: npm install && npm run prod

      - name: Deploy an App Engine app
        id: deploy-app
        uses: google-github-actions/deploy-appengine@v0.3.1
        with:
          project_id: ${{ secrets.GCR_PROJECT }}
          deliverables: app-testing.yaml
          credentials: ${{ secrets.GCR_SA_KEY}}
          version: v1