name: Google Cloud Run Deploy
# https://github.com/google-github-actions/setup-gcloud
on:
  push:
    branches:
      - main

jobs:

  deploy-gcr:
    name: Deploy to GCP
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCR_PROJECT }}
        service_account_key: ${{ secrets.GCR_SA_KEY }}
        export_default_credentials: true

    - name: set project
      run: gcloud config set project ${{ secrets.GCR_PROJECT }}


    - name: npm install, build
      run: |
          npm install
          npm run build
    
    # Runs a set of commands using the runners shell
    - name: GCP deploy
      run: |
        gcloud app deploy --quiet
